import pytest
from google.api_core.exceptions import NotFound, ServiceUnavailable
from google.genai.errors import ClientError

from services import agent_builder


def test_live_brief_uses_adk_generator_and_mcp_context(monkeypatch):
    class FakeGitLabClient:
        def fetch_demo_activity(self):
            return {
                "issues": [
                    {
                        "id": "412",
                        "iid": 1,
                        "project": "billing",
                        "title": "[billing/#412] Add invoice empty state",
                        "labels": ["billing", "good-first-issue"],
                        "assignee": None,
                        "state": "opened",
                        "web_url": "https://gitlab.com/demo/-/issues/1",
                    }
                ],
                "merge_requests": [],
                "mcp_tools": ["glab_issue_list", "glab_api"],
            }

    class FakeAdkRunner:
        calls = []

        def generate_json(self, *, task, payload):
            self.calls.append((task, payload))
            return {
                "brief": {
                    "now": {
                        "title": "Right Now",
                        "body": "Generated by Gemini through ADK.",
                        "sources": ["GitLab MCP", "Notion"],
                    }
                }
            }

    monkeypatch.setenv("FLUX_AGENT_MODE", "live")
    monkeypatch.setattr(agent_builder, "GitLabMcpClient", FakeGitLabClient)
    monkeypatch.setattr(agent_builder, "AdkGeminiRunner", FakeAdkRunner)
    monkeypatch.setattr(
        agent_builder,
        "load_team_guide_text",
        lambda: ("## The Team\nMarcus owns auth.", "live_notion"),
    )

    brief = agent_builder.build_flux_brief()

    assert brief["now"]["body"] == "Generated by Gemini through ADK."
    assert FakeAdkRunner.calls[0][0] == "brief"
    assert FakeAdkRunner.calls[0][1]["gitlab_activity"]["mcp_tools"] == [
        "glab_issue_list",
        "glab_api",
    ]


def test_live_chat_returns_action_from_adk(monkeypatch):
    class FakeAdkRunner:
        def generate_json(self, *, task, payload):
            assert task == "chat"
            assert payload["message"] == "Assign issue #412 to me"
            return {
                "answer": "I can assign issue #412 after confirmation.",
                "sources": ["GitLab MCP"],
                "action": {
                    "type": "assign_issue",
                    "issue_id": "412",
                    "project": "billing",
                    "username": "assafbar",
                },
            }

    monkeypatch.setenv("FLUX_AGENT_MODE", "live")
    monkeypatch.setattr(agent_builder, "AdkGeminiRunner", FakeAdkRunner)
    monkeypatch.setattr(agent_builder, "load_live_context", lambda: {"ok": True})

    response = agent_builder.answer_flux_question("Assign issue #412 to me", "assafbar")

    assert response["sources"] == ["GitLab MCP"]
    assert response["action"]["type"] == "assign_issue"


def test_demo_mode_still_uses_deterministic_fallback(monkeypatch):
    monkeypatch.setenv("FLUX_AGENT_MODE", "demo")

    response = agent_builder.answer_flux_question("Who owns auth?", "assafbar")

    assert "Marcus" in response["answer"]
    assert response["action"] is None


@pytest.mark.anyio
async def test_vertex_location_retry_uses_configured_location_then_fallbacks(monkeypatch):
    monkeypatch.setenv("GOOGLE_CLOUD_LOCATION", "us-east4")
    attempted_locations = []

    async def fake_agent_run(model):
        attempted_locations.append((model, agent_builder.os.environ["GOOGLE_CLOUD_LOCATION"]))
        if len(attempted_locations) == 1:
            raise NotFound("model not available there")
        return {"ok": True}

    result = await agent_builder._try_vertex_locations("gemini-2.0-flash", fake_agent_run)

    assert result == {"ok": True}
    assert attempted_locations == [
        ("gemini-2.0-flash", "us-east4"),
        ("gemini-2.0-flash", "us-central1"),
    ]


@pytest.mark.anyio
async def test_vertex_location_retry_raises_after_retriable_failures(monkeypatch):
    monkeypatch.delenv("GOOGLE_CLOUD_LOCATION", raising=False)
    attempted_locations = []

    async def fake_agent_run(model):
        attempted_locations.append(agent_builder.os.environ["GOOGLE_CLOUD_LOCATION"])
        raise ServiceUnavailable("region unavailable")

    with pytest.raises(ServiceUnavailable):
        await agent_builder._try_vertex_locations("gemini-2.0-flash", fake_agent_run)

    assert attempted_locations == ["us-central1", "us-east4", "us-west1", "europe-west4"]


@pytest.mark.anyio
async def test_vertex_location_retry_handles_genai_client_404(monkeypatch):
    monkeypatch.delenv("GOOGLE_CLOUD_LOCATION", raising=False)
    attempted_locations = []

    async def fake_agent_run(model):
        attempted_locations.append(agent_builder.os.environ["GOOGLE_CLOUD_LOCATION"])
        if len(attempted_locations) == 1:
            raise ClientError(404, {"error": {"status": "NOT_FOUND"}})
        return {"ok": True}

    result = await agent_builder._try_vertex_locations("gemini-2.0-flash", fake_agent_run)

    assert result == {"ok": True}
    assert attempted_locations == ["us-central1", "us-east4"]
